[project]
name = "pydistrict-github-io"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiohttp==3.7.3",
    "ghp-import2==1.0.1",
    "nikola==8.3.1",
    "watchdog==1.0.2",
]
